import os
import sys
from PIL import Image, ImageDraw, ImageFont, ImageFilter

if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

# Input background generated by Flux
bg_path = "ultra_crisp_Diwali_Diya_UltraCrisp.png"
if not os.path.exists(bg_path):
    print("❌ Base image not found!")
    exit(1)

base_img = Image.open(bg_path).convert("RGBA")
width, height = base_img.size # 1024x1024

# Create transparent overlay for typography and UI elements
overlay = Image.new("RGBA", (width, height), (0, 0, 0, 0))
draw = ImageDraw.Draw(overlay)

# Try loading modern fonts or fallback
def get_font(size, bold=False):
    font_names = ["arialbd.ttf" if bold else "arial.ttf", "segoeuib.ttf" if bold else "segoeui.ttf", "calibrib.ttf"]
    for f in font_names:
        try:
            return ImageFont.truetype(f, size)
        except:
            continue
    return ImageFont.load_default()

font_brand = get_font(28, bold=True)
font_super_title = get_font(22, bold=False)
font_hero_title = get_font(68, bold=True)
font_sub = get_font(26, bold=False)
font_badge = get_font(24, bold=True)
font_cta = get_font(22, bold=True)

# -----------------------------------------------------------------------------
# 1. TOP BRANDING HEADER
# -----------------------------------------------------------------------------
brand_text = "T A L I Y O  C R E A T I V E"
draw.text((width // 2, 60), brand_text, fill=(255, 215, 0, 220), font=font_brand, anchor="mm")

# Subtle golden separator line
draw.line([(width // 2 - 120, 85), (width // 2 + 120, 85)], fill=(255, 184, 0, 160), width=2)

# -----------------------------------------------------------------------------
# 2. HERO HEADLINE IN NEGATIVE SPACE (TOP 40%)
# -----------------------------------------------------------------------------
draw.text((width // 2, 140), "✨ FESTIVE EXCELLENCE 2026", fill=(255, 184, 0, 240), font=font_super_title, anchor="mm")
draw.text((width // 2, 210), "ILLUMINATE", fill=(255, 255, 255, 255), font=font_hero_title, anchor="mm")
draw.text((width // 2, 275), "YOUR BRAND IDENTITY", fill=(255, 215, 100, 255), font=get_font(42, bold=True), anchor="mm")
draw.text((width // 2, 335), "Craft bespoke campaigns that command attention.", fill=(200, 210, 225, 220), font=font_sub, anchor="mm")

# -----------------------------------------------------------------------------
# 3. BOTTOM FESTIVE BADGE & CALL TO ACTION
# -----------------------------------------------------------------------------
# Floating glassmorphism pill badge at bottom
badge_box = [width // 2 - 180, height - 120, width // 2 + 180, height - 65]
draw.rounded_rectangle(badge_box, radius=28, fill=(20, 30, 48, 210), outline=(255, 184, 0, 200), width=2)
draw.text((width // 2, height - 92), "🎁 FLAT 35% FESTIVE BONUS", fill=(255, 215, 0, 255), font=font_badge, anchor="mm")

# Footer handles
draw.text((width // 2, height - 35), "@virajverse  •  taliyo.com", fill=(160, 175, 200, 180), font=font_cta, anchor="mm")

# Subtle outer gold frame
draw.rectangle([20, 20, width - 20, height - 20], outline=(255, 184, 0, 70), width=1)

# Composite together
final_post = Image.alpha_composite(base_img, overlay).convert("RGB")
output_path = "finished_instagram_post_diwali.png"
final_post.save(output_path, "PNG", quality=95)

print(f"🎉 Generated Complete Instagram/Facebook Post: {output_path} ({os.path.getsize(output_path)/1024:.1f} KB)")
