import { runUnifiedGraphicDesignerAgent } from '../src/services/autonomousDesignerAgent.js';

async function verifyLiveLLMExecution() {
  console.log('=' .repeat(80));
  console.log('🤖 LIVE LLM + AGENT EXECUTION VERIFICATION');
  console.log('=' .repeat(80));

  // Test 1: Casual Hinglish Prompt requiring LLM Intent Perception & 3D Render Crafting
  const prompt1 = 'Organic matcha tea brand ke liye 3d japanese ceramic bowl render banao dark background me';
  console.log(`\n📌 [TEST 1] User Casual Input:\n"${prompt1}"`);
  console.log('⏳ Calling LLM Front Dispatcher to analyze intent and craft 3D visual formula...');
  
  const start1 = Date.now();
  const res1 = await runUnifiedGraphicDesignerAgent(prompt1);
  const time1 = Date.now() - start1;

  console.log(`✅ [TEST 1 RESULT] Completed in ${time1}ms:`);
  console.log(`  • Action Determined by LLM: ${res1.action}`);
  console.log(`  • Image Rendered: ${res1.imageBuffer ? `Yes (${res1.imageBuffer.length} bytes)` : 'No'}`);
  console.log(`  • Designer Brief Generated by LLM:\n${res1.deliverable.slice(0, 300)}...`);

  // Test 2: Marketing Campaign Ideation requiring Multi-Archetype Reasoning
  const prompt2 = 'Suggest high-converting Instagram carousel concepts for a fintech crypto wallet app';
  console.log(`\n📌 [TEST 2] User Campaign Brief:\n"${prompt2}"`);
  console.log('⏳ Calling LLM Multi-Archetype Ideation Engine...');

  const start2 = Date.now();
  const res2 = await runUnifiedGraphicDesignerAgent(prompt2);
  const time2 = Date.now() - start2;

  console.log(`✅ [TEST 2 RESULT] Completed in ${time2}ms:`);
  console.log(`  • Action Determined by LLM: ${res2.action}`);
  console.log(`  • Ideas Synthesized by LLM:\n${res2.deliverable.slice(0, 400)}...`);

  console.log('\n' + '=' .repeat(80));
  console.log('🎉 VERIFICATION RESULT: LLM IS FULLY ACTIVE & INTEGRATED!');
  console.log('=' .repeat(80));
}

verifyLiveLLMExecution().catch(err => {
  console.error('❌ Error during LLM test:', err);
});
